### ISSUE TITLE
Can't assign string to a variable without using printf

### ISSUE THREAD

**Issue by JBBgameich** [fiji-flo/gtmpl-rust#15]
This seems to work in go
```
{{ $suite := "testing" }}
```
while for gtmpl-rust it seems to be required to use printf, which is not really a problem but breaks compatibility with existing templates.
```
{{ $suite := printf "testing" }}
```
I'm sorry in case this is explicitly not supported and I just missed it.

**Comment by fiji-flo** [comment]
```
{{ with $foo := "bar" }}{{ $foo }}{{ end }}
```
Would that be another test case. That was definitely a bug. Fixing it right away. Thanks for reporting.

**Comment by JBBgameich** [comment]
Thank you for fixing! I'm using your crate from python btw because I found it easier to write bindings for rust than for go :)
