### ISSUE TITLE
Indentation of Dynamic Templates

### ISSUE THREAD

**Issue by sstubbs** [fiji-flo/gtmpl-rust#20]
Hi,

Sorry for all the questions. This lib is just working so well I've pretty much got everything I need to finish what I'm working on so want to try get it done. Last issue which I'm not really sure how to deal with is indentation when inserting dynamic templates.

In this file I'm creating templates https://github.com/sstubbs/postgres-xl-operator/blob/master/templates/_operator_helpers.tpl. This one is creating variables https://github.com/sstubbs/postgres-xl-operator/blob/master/templates/_operator_vars.tpl and then currently there is just one main template loading these at https://github.com/sstubbs/postgres-xl-operator/blob/master/templates/main.tpl

I've been trying various ways and I can't get the inserted dynamic template indented. It respects the whitespace for variables both from the context and others created in the template but not for dynamic templates.

Go has `| indent`

Can you think of a way I can do this?

**Comment by fiji-flo** [comment]
I added support to `indent` to https://crates.io/crates/sprig

That should work. Just add it via `add_funcs` like this https://github.com/fiji-flo/myke/blob/master/src/myke/template.rs#L43

Can you test if that works?

**Comment by sstubbs** [comment]
ok thanks I've added it in this commit https://github.com/sstubbs/postgres-xl-operator/commit/c9cd88cd862b0334580493debde0585d9b24adb1 abbrev is working for the variables so I think I've set it up properly. However when I try 
```
{{ indent 5 $test }}
{{ indent 5 .name }}
```
or
```
{{ $test | indent 5 }}
{{ .name | indent 5 }}
```
I get this error
```
template: :34:function indent not defined
```

**Comment by sstubbs** [comment]
After looking in the source. The crate doesn't seem to reflect this being added although it is added in the GitHub repo.

**Comment by fiji-flo** [comment]
My bad.

Can you add sprig from master as a dependency:
```toml
sprig = { git = "https://github.com/fiji-flo/sprig-rust" }
```
If that works I'll release this as `0.1.3`

**Comment by sstubbs** [comment]
ok thanks it works for the variables but for the the dynamic template I get the following error:
```
template: :40:unexpected template in operand
```

**Comment by fiji-flo** [comment]
Just to check. Did you test this in go? I'm reading through the doc there and I'm not sure that's possible. `template` isn't a pipeline, is it?
I'll dig a little, but if you have an example in go that would help.

**Comment by sstubbs** [comment]
I don't actually see this. You right. All I can find is this https://stackoverflow.com/questions/43821989/how-to-indent-content-of-included-template I am porting over a helm project to use this and was just trying to refactor things as much as possible and just assumed this would work but if this isn't even a feature of go it's definitely not worth adding it here. I will not use templates where indentation is required. Sorry if I wasted your time on this.

**Comment by sstubbs** [comment]
The indent feature you added works well for variables though. Would it be possible to do the `0.1.3` release with that so I can use it in a more stable way?

**Comment by sstubbs** [comment]
No rush if there is something else you waiting on to do this though.

**Comment by fiji-flo** [comment]
Sorry, had a busy week. `0.1.3` is published, just adding `indent`.
