### ISSUE TITLE
Enumeration in range

### ISSUE THREAD

**Issue by sstubbs** [fiji-flo/gtmpl-rust#21]
Hi,

Do you know the best way I could get the iteration count to replicate the below which is currently working in helm?

```
  {{- range $i, $val := $config_col.init }}
  init_{{ printf "%05d" $i }}_{{ $val.name }}: |-
{{ $val.script | indent 4}}
  {{- end }}
```

**Comment by fiji-flo** [comment]
that should work work https://github.com/fiji-flo/gtmpl-rust/blob/master/src/exec.rs#L742
 
I guess `init` is an array?

**Comment by sstubbs** [comment]
Ok thanks for this . It's a vec of struct. https://github.com/sstubbs/postgres-xl-operator/blob/master/src/structs.rs#L220 I will try various ways and see how I can get the iteration number. It looks like this is supported from your tests.

**Comment by sstubbs** [comment]
This works great! thank you this issue can be closed.

**Comment by fiji-flo** [comment]
:+1:
